// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCScRucA7l3xPfEtccayOrvYeWgJ8kQ9VU',
    appId: '1:109157925075:web:b80ce6c81d4caf6fe05426',
    messagingSenderId: '109157925075',
    projectId: 'bank-of-mom-and-dad-ho',
    authDomain: 'bank-of-mom-and-dad-ho.firebaseapp.com',
    storageBucket: 'bank-of-mom-and-dad-ho.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC668HcOjW0KfXRO_IdITg9hKaqUmUv1Gg',
    appId: '1:109157925075:ios:d1f8b8087f9391c2e05426',
    messagingSenderId: '109157925075',
    projectId: 'bank-of-mom-and-dad-ho',
    storageBucket: 'bank-of-mom-and-dad-ho.firebasestorage.app',
    iosClientId: '109157925075-3k9ubr9o7b7p9h44aj263iiu1bfo6kic.apps.googleusercontent.com',
    iosBundleId: 'com.eculeus.bomad',
  );
}
